name: Build

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:


jobs:
  build-cmake:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
        - os: ubuntu-latest
          cmake-args: -G Ninja -DSERVER=OFF
          env:
            CFLAGS: -Wdeclaration-after-statement -Werror
            CXXFLAGS: -Werror
        - os: macOS-latest
          cmake-args: -G Ninja -DSERVER=OFF
          env:
            CFLAGS: -Wdeclaration-after-statement -Werror
            CXXFLAGS: -Werror
            CMAKE_PREFIX_PATH: /opt/homebrew/include/:$CMAKE_PREFIX_PATH
        - os: windows-latest
          cmake-args: -A x64 -DSERVER=OFF
          env:
            CFLAGS: /WX
            CXXFLAGS: /WX
            LDFLAGS: /WX

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Checkout SDL3
      if: contains(matrix.os, 'ubuntu')
      uses: actions/checkout@v4
      with:
        repository: libsdl-org/SDL
        ref: release-3.2.18
        path: ./SDL

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -yy
        sudo apt-get install build-essential git cmake libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libwayland-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libibus-1.0-dev libdbus-1-dev libudev-dev libinput-dev libts-dev libjpeg-dev libwebp-dev -y
        sudo apt-get install pkg-config libcurl4-openssl-dev libfreetype6-dev cmake ninja-build libogg-dev libopus-dev libopusfile-dev -y
        cd SDL
        cmake . -DCMAKE_BUILD_TYPE=Release
        sudo make install

    - name: Prepare Libraries
      if: contains(matrix.os, 'windows')
      uses: actions/checkout@v4
      with:
        repository: NewTeeworldsCN/carbon-libraries
        ref: main
        path: ./carbon-libraries

    - name: Prepare MacOS
      if: contains(matrix.os, 'macOS')
      run: |
        brew update || true
        brew install sdl3 opusfile
        sudo rm -rf /Library/Developer/CommandLineTools

    - name: Build in debug mode
      env: ${{ matrix.env }}
      run: |
        mkdir debug
        cd debug
        ${{ matrix.cmake-path }}cmake --version
        ${{ matrix.cmake-path }}cmake ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=Debug -Werror=dev -DDOWNLOAD_GTEST=ON -DDEV=ON -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG=. ..
        ${{ matrix.cmake-path }}cmake --build . --config Debug ${{ matrix.build-args }} --target everything
    - name: Test debug
      run: |
        cd debug
        ${{ matrix.cmake-path }}cmake --build . --config Debug ${{ matrix.build-args }} --target run_tests

    - name: Build in release mode
      env: ${{ matrix.env }}
      run: |
        mkdir release
        cd release
        ${{ matrix.cmake-path }}cmake ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=Release -Werror=dev -DDOWNLOAD_GTEST=ON -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=. ..
        ${{ matrix.cmake-path }}cmake --build . --config Release ${{ matrix.build-args }} --target everything
    - name: Test release
      run: |
        cd release
        ${{ matrix.cmake-path }}cmake --build . --config Release ${{ matrix.build-args }} --target run_tests

    - name: Package
      run: |
        cd release
        ${{ matrix.cmake-path }}cmake --build . --config Release ${{ matrix.build-args }} --target package_default

    - name: Upload Artifacts
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: Carbon-${{ matrix.os }}
        path: release/package/*
    - name: Prepare for Release
      run: |
        mkdir result
    - name: Download artifact for Release
      uses: dawidd6/action-download-artifact@v11
      if: github.ref_type == 'tag'
      with:
        name: Carbon-${{ matrix.os }}
        run_id: ${{ github.event.workflow_run.id }}
        path: result/
        skip_unpack: true
    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: result/*
